### ISSUE TITLE
Create a component to animate the `<details>` element

### ISSUE THREAD

**Issue by Ambient-Impact** [Ambient-Impact/drupal-ambientimpact-ux#2]
[How to Animate the Details Element | CSS-Tricks](https://css-tricks.com/how-to-animate-the-details-element/) provides a basic (if messy) implementation for animating the [`<details>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) which can be adapted.

# Tasks for MVP

- [x] Implement the basic component.
- [x] Implement a demo.
- [x]  Accessibility: Rework clipping/overflow to not clip the focus outline.
- [x] Accessibility: Implement [`prefers-reduced-motion` media feature](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion), opening and closing instantly without sliding.
- [x]  Accessibility: Remove the `click` event handler and remove manual toggling of the `open` property; replace with `toggle` event handler which doesn't interfere or change the the `open` property; use the closing class to force displaying the content until the animation completes; [see this comment for the accessibility problem with the click handler approach](https://css-tricks.com/how-to-animate-the-details-element/#comment-1802599); see also [`details.module.css` in the Stable theme](https://git.drupalcode.org/project/stable/-/blob/9ff8c0f10c74015d488a5e477ccfbe2def8994cc/css/system/components/details.module.css) for a selector we need to override.
- [x] Test and support the `<details>` already being open on attach/construct.
- [x] Update the inline height and custom properties using [`ResizeObserver`](https://developer.mozilla.org/en-US/docs/Web/API/Resize_Observer_API)s on  the `<summary>` and cloned content elements.
- [x] Update the cloned content before an animation so that we don't end up with out of date measured heights; this could be done via a [`MutationObserver`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) but that would probably result in more work for the browser than is necessary and could cause unexpected changes during an animation if not implemented taking that into account.

# Follow up tasks

- [x] Rework the demo content to nest more info about the technique and reasons for various things inside the `<details>` themselves.
- [x] Support nested `<details>` elements; animation currently does not take into account the height of nested elements and behaves unexpectedly due to inline `height`.
- [x] Add a Material ripple effect to the `<summary>` element on toggle; note that this is more complicated than expected due to the old code in the Material ripple component combined with the way we're laying out and styling the `<summary>` background. 🤦
- [x] Decide what to do about the disparity between the fact that the component primarily exists just for animation and that it's called a generic `details` component: do we rename the component and/or set it as a sub-component that provides the animation, or do we rename the class to a more generic format?
- [x] Demo: Add unstyled but animated; currently doesn't animate correctly if attempted but is hopefully relatively simple to fix.
- [ ] Add Wikipedia-like collapsible sections styling; see [any article on mobile site](https://en.m.wikipedia.org/wiki/Neurocracy).
- [ ] UX improvement: if content height is greater than a certain threshold (`100vh`?), add a button at the end to collapse/close the element.
- [ ] Add more thorough checking for unexpected values, e.g. content height of zero or `NaN`, so that we can degrade gracefully without blocking/obscuring content.
- [ ] UX improvement: scale open/close duration based on height, so taller content takes a bit longer and doesn't feel weirdly fast.
- [ ] Combine all state tracking into a single property on the class as there's no good point having separate flags for them because the element can only ever be in one state at a time and not multiple; this just adds more points of potential failure/bugs.
- [ ] Related to above, test that state tracking is as accurate as possible so that rapid clicking doesn't break the animation due to async code getting out of sync (ironically) with the state.
- [ ] Trigger custom events when opening and closing animations have completed; can the `toggle` event stand in for open start and close start events or should we also trigger those too?
